import type { NextPage } from 'next'
import Head from 'next/head'
import useSWR from 'swr'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useEffect } from 'react'
import { i18n, useTranslation } from 'next-i18next'
import { useRouter } from 'next/router'


const Home: NextPage = () => {
  const url = 'https://gist.githubusercontent.com/bu3alwa/145414b78718a0749f6d6a4148d1b779/raw/9da29960ed7ad898d0f43f6f4eee9a0199edaef3/translation.json'
  const fetcher = async (url: string) => await axios.get(url).then((res) => res.data)
  const { locale } = useRouter()

  const { data, error } = useSWR(url, (url) => fetcher(url))

  useEffect(() => {
    if (!data || !locale) return
    console.log(data)
    console.log(i18n)
    i18n?.addResourceBundle(locale, 'translation', data, true, true) 
  })

  const { t, ready } = useTranslation('translation')

  if (!ready) return <div>Loading...</div>

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <p>
            {t('name') as string}
          </p>
        </div>
      </main>
    </div>
  )
}

export default Home
